# Generated by Django 3.0.6 on 2020-06-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_braintree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='braintree_id',
        ),
        migrations.AddField(
            model_name='order',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
